stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: denyacore/hello-kubernetes

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE_NAME

deploy:
  stage: deploy
  script:
    - echo "im alive"