image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_GITLAB/$CI_REGISTRY_IMAGE_GITLAB

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER_GITLAB" -p "$CI_REGISTRY_PASSWORD_GITLAB" $CI_REGISTRY_GITLAB
  - apk add curl

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME -f src/app/Dockerfile .
    - docker push $DOCKER_IMAGE_NAME

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_IMAGE_NAME
    - docker run -d -p 8000:80 $DOCKER_IMAGE_NAME    
    - sleep 10 # Даем контейнеру время для запуска
    - CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q --filter "ancestor=$DOCKER_IMAGE_NAME"))
    - docker ps -a # Показываем список запущенных контейнеров
    # - docker ps -q -n 1 | xargs docker logs # логи последнего запущенного контейнера
    # - docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q --filter "ancestor=$DOCKER_IMAGE_NAME") # находим ip контейнера
    # - curl -s http://$CONTAINER_IP:8080 # Проверяем доступность вашего приложения (замените URL на фактический, если необходимо)