image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_GITLAB/$CI_REGISTRY_IMAGE_GITLAB

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER_GITLAB" -p "$CI_REGISTRY_PASSWORD_GITLAB" $CI_REGISTRY_GITLAB
  - apk add curl

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME -f src/app/Dockerfile .
    - docker push $DOCKER_IMAGE_NAME

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_IMAGE_NAME
    - docker run -d -p 8080:8080 -e HOST=0.0.0.0 $DOCKER_IMAGE_NAME # Запускаем контейнер с образом
    - sleep 10 # Даем контейнеру время для запуска (может потребоваться больше времени, в зависимости от вашего приложения)
    - docker ps -a # Показываем список запущенных контейнеров
    - docker ps -q -n 1 | xargs docker logs
    - curl -s http://localhost:8080 # Проверяем доступность вашего приложения (замените URL на фактический, если необходимо)
