image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - cd E:/Dev/tensortest/hello-kubernetes/.devcontainer # Переходим в директорию с Dockerfile для DevContainer
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME

deploy:
  stage: deploy
  script:
    - echo "Deployment script goes here" # Замените эту строку на скрипт развертывания вашего проекта, используя собранный Docker-образ
  only:
    - master
