image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - mkdir -p /tmp/build-context # Создаем временную директорию внутри контейнера
    - cp -r .devcontainer/* /tmp/build-context/ # Копируем файлы и директории во временную директорию
    - cd /tmp/build-context # Переходим во временную директорию
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME

deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_IMAGE_NAME # Пуллим собранный образ из Docker Registry
    - docker run -d -p 8080:80 $DOCKER_IMAGE_NAME # Запускаем контейнер с образом
  only:
    - master
